[package]
name = "flowsdn-bpf-loader"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
flowsdn-bpf-abi = { path = "../flowsdn-bpf-abi", version = "=0.14.0" }
aya = { version = "=0.14.0", optional = true }

[features]
default = []
kernel = ["dep:aya"]
