[package]
name = "flowsdn-bpftest"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
aya = "=0.14.0"
nix = { version = "=0.30.1", default-features = false, features = ["sched"] }
flowsdn-bpf-abi = { path = "../flowsdn-bpf-abi", version = "=0.14.0" }
flowsdn-bpf-loader = { path = "../flowsdn-bpf-loader", version = "=0.14.0", features = ["kernel"] }

[[bin]]
name = "flowsdn-endpoint-test"
path = "src/bin/endpoint.rs"
