[package]
name = "flowsdn-k8s"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
serde_json.workspace = true
flowsdn-table = { path = "../flowsdn-table", version = "=0.14.0" }

[dev-dependencies]
tokio = { workspace = true, features = ["rt"] }

[lints]
workspace = true
