[package]
name = "flowsdn-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true
[dependencies]
flowsdn-clustermesh = { path = "../flowsdn-clustermesh", version = "=0.14.0" }
[dev-dependencies]
serde_json.workspace = true
yaml-rust2.workspace = true
[lints]
workspace = true
