// Classification tables from the original flowsdn inventory harvester.
pub const ENTRY_HELPERS: &[(&str, &str)] = &[
    ("netdev_receive_packet", "from_netdev"),
    ("netdev_send_packet", "to_netdev"),
    ("host_receive_packet", "to_host"),
    ("host_send_packet", "from_host"),
    ("pod_send_packet", "from_container"),
    ("pod_receive_packet_by_tailcall", "lxc_policy"),
    ("pod_receive_packet", "to_container"),
    ("overlay_receive_packet", "from_overlay"),
    ("overlay_send_packet", "to_overlay"),
    ("xdp_receive_packet", "xdp_entry"),
];
pub const ENTRY_HDR: &[(&str, &str)] = &[
    ("lib/bpf_host.h", "host"),
    ("lib/bpf_lxc.h", "lxc"),
    ("lib/bpf_overlay.h", "overlay"),
    ("lib/bpf_xdp.h", "xdp"),
];
pub const SRC_OBJ: &[(&str, &str)] = &[
    ("bpf_host.c", "host"),
    ("bpf_lxc.c", "lxc"),
    ("bpf_overlay.c", "overlay"),
    ("bpf_xdp.c", "xdp"),
    ("bpf_sock.c", "sock"),
    ("bpf_sock_term.c", "sock_term"),
    ("bpf_wireguard.c", "wireguard"),
];
pub const LIB_UNIT: &[(&str, &str)] = &[
    ("lib/conntrack.h", "conntrack"),
    ("lib/conntrack_map.h", "conntrack"),
    ("lib/nat.h", "nat"),
    ("lib/lb.h", "lb"),
    ("lib/fib.h", "fib"),
    ("lib/ipfrag.h", "ipfrag"),
    ("lib/ipv6.h", "ipv6"),
    ("lib/policy.h", "policy"),
    ("lib/ratelimit.h", "ratelimit"),
    ("lib/drop.h", "drop"),
    ("lib/dbg.h", "dbg"),
    ("lib/ip_options.h", "ip_options"),
    ("lib/mcast.h", "mcast"),
    ("lib/classifiers.h", "classifiers"),
    ("lib/identity.h", "identity"),
    ("lib/jhash.h", "jhash"),
    ("lib/encrypt.h", "encrypt"),
    ("lib/wireguard.h", "wireguard"),
    ("lib/ipsec.h", "ipsec"),
    ("lib/egressgw.h", "egressgw"),
    ("lib/eps.h", "eps"),
    ("lib/trace.h", "trace"),
    ("bpf/builtins.h", "builtins"),
    ("lib/tailcall.h", "tailcall"),
    ("lib/l2_responder.h", "l2_responder"),
    ("lib/local_delivery.h", "local_delivery"),
    ("lib/nodeport.h", "nodeport"),
    ("lib/srv6.h", "srv6"),
    ("lib/csum.h", "csum"),
    ("lib/proxy.h", "proxy"),
    ("lib/icmp6.h", "icmp6"),
    ("lib/edt.h", "edt"),
    ("lib/act.h", "act"),
    ("lib/ipcache.h", "ipcache"),
    ("../lib/mcast.h", "mcast"),
];
pub const SEED_HDR: &[(&str, &str)] = &[
    ("lib/endpoint.h", "endpoints"),
    ("lib/ipcache.h", "ipcache"),
    ("lib/lb.h", "services"),
    ("lib/policy.h", "policy"),
    ("lib/node.h", "nodes"),
    ("lib/metrics.h", "metrics"),
    ("lib/network_device.h", "devices"),
    ("lib/subnet.h", "subnets"),
    ("lib/egressgw_policy.h", "egressgw_policy"),
    ("lib/clear.h", "clear"),
    ("lib/icmp.h", "icmp"),
    ("lib/ipsec.h", "ipsec_state"),
];
pub const FEAT_PREFIX: &[&str] = &[
    "ENABLE_",
    "SKIP_",
    "HAVE_",
    "TUNNEL_",
    "ENCAP",
    "DSR_",
    "IS_BPF_",
    "SUPPORT_",
    "ENCRYPT",
    "NATIVE_",
    "HOST_NODE",
    "HOST_NETNS",
    "SECLABEL",
    "LB_DEFAULT_ALG",
    "NORTH_SOUTH_TEST",
    "EAST_WEST_TEST",
    "ATTACHMENT_",
];
pub const M1_OVERRIDE: &[&str] = &[
    "classifiers_l2_dev.c",
    "classifiers_l3_dev.c",
    "icmp_error_revnat.c",
    "tc_nodeport_l3_dev.c",
    "tc_nodeport_l3_dev_to_tunnel.c",
];
pub const M2_OVERRIDE: &[&str] = &[
    "host_only_socket_lb_test.c",
    "host_proxy.c",
    "hostfw_bpf_masq.c",
    "hostfw_host_iptables.c",
    "jhash_test.c",
    "l7_lb_hairpin_netdev.c",
    "l7_lb_local_backend_host.c",
    "l7_lb_local_backend_pod.c",
    "session_affinity_maglev_test.c",
    "session_affinity_test.c",
    "skip_lb_xlate_lrp_per_packet_lb.c",
    "skip_lb_xlate_socket_lb.c",
    "tc_policy_reject_response_test.c",
    "wildcard_lookup.c",
];
pub const M3_OVERRIDE: &[&str] = &[
    "destroy_sock_socket_lb.c",
    "eni_nlb_symetric_routing_host.c",
    "ip_options_trace_id.c",
    "l4lb_ipip_health_check_host.c",
    "mcast_tests.c",
    "tc_l2_announcement.c",
    "tc_l2_announcement6.c",
    "tc_nodeport_l3_wireguard.c",
    "tc_nodeport_lb4_ipip_termination.c",
    "tc_nodeport_lb6_ipip_termination.c",
    "tc_srv6_decap.c",
    "tc_srv6_encap.c",
];
pub const M3_FEATS: &[&str] = &[
    "ENABLE_CLUSTER_AWARE_ADDRESSING",
    "ENABLE_EGRESS_GATEWAY",
    "ENABLE_HEALTH_CHECK",
    "ENABLE_INTER_CLUSTER_SNAT",
    "ENABLE_IPSEC",
    "ENABLE_MULTICAST",
    "ENABLE_NODE_ENCRYPTION",
    "ENABLE_SRV6",
    "ENABLE_SRV6_SRH_ENCAP",
    "ENABLE_WIREGUARD",
    "ENCRYPTION_STRICT_MODE_EGRESS",
    "ENCRYPT_KEY",
];
pub const M2_FEATS: &[&str] = &[
    "ENABLE_HOST_FIREWALL",
    "ENABLE_L7_LB",
    "ENABLE_NODEPORT_ACCELERATION",
];
