use flowsdn_harvest_bpf_cases::{COMMIT, equivalent, harvest, load};
use std::{env, error::Error, fs, path::PathBuf, process::Command};

fn main() -> Result<(), Box<dyn Error>> {
    let mut reference = None;
    let mut output = None;
    let mut check = None;
    let mut date = "2026-09-07".to_owned();
    let mut args = env::args().skip(1);
    while let Some(arg) = args.next() {
        if arg == "--help" {
            println!(
                "flowsdn-harvest-bpf-cases --reference CHECKOUT [--check CASES.toml | --output CASES.toml] [--date YYYY-MM-DD]"
            );
            return Ok(());
        }
        let value = args
            .next()
            .ok_or_else(|| format!("missing value for {arg}"))?;
        match arg.as_str() {
            "--reference" => reference = Some(PathBuf::from(value)),
            "--output" => output = Some(PathBuf::from(value)),
            "--check" => check = Some(PathBuf::from(value)),
            "--date" => date = value,
            _ => return Err(format!("unknown argument: {arg}").into()),
        }
    }
    if output.is_some() && check.is_some() {
        return Err("choose either --check or --output".into());
    }
    let reference = reference.ok_or("--reference is required")?;
    let revision = Command::new("git")
        .arg("-C")
        .arg(&reference)
        .args(["rev-parse", "HEAD"])
        .output()?;
    if !revision.status.success() || String::from_utf8_lossy(&revision.stdout).trim() != COMMIT {
        return Err(format!("reference must be checked out at {COMMIT}").into());
    }
    // A dirty reference would undermine the claimed provenance.
    let status = Command::new("git")
        .arg("-C")
        .arg(&reference)
        .args([
            "status",
            "--porcelain",
            "--untracked-files=all",
            "--",
            "bpf/tests",
        ])
        .output()?;
    if !status.status.success() || !status.stdout.is_empty() {
        return Err("reference bpf/tests must be clean".into());
    }
    let inventory = harvest(&load(&reference.join("bpf/tests"))?, &date)?;
    if let Some(check) = check {
        let existing = toml::Value::Table(fs::read_to_string(check)?.parse::<toml::Table>()?);
        if !equivalent(inventory.clone(), existing) {
            return Err("harvest differs from the committed inventory".into());
        }
        println!("Inventory matches: every case, feature, entrypoint and milestone is preserved.");
    } else {
        let header = "# flowsdn BPF test inventory. Generated by tools/harvest-bpf-cases (Rust).\n# Reference: Cilium v1.20.1 / 7d68cfb394, bpf/tests.\n# SPDX-License-Identifier: BSD-2-Clause; Copyright Authors of Cilium.\n# Identifiers and structure only; no C source copied. See PROVENANCE and NOTICE.\n# Hand-maintained porting status belongs in PORTED.toml.\n\n";
        let contents = format!("{header}{}", toml::to_string_pretty(&inventory)?);
        if let Some(output) = output {
            fs::write(output, contents)?;
        } else {
            print!("{contents}");
        }
    }
    Ok(())
}
