apiVersion: v1
kind: Namespace
metadata:
  name: flowsdn-system
  labels:
    pod-security.kubernetes.io/enforce: privileged
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flowsdn-agent
  namespace: flowsdn-system
automountServiceAccountToken: false
