[package]
name = "flowsdn-clustermesh"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true
[dependencies]
serde_json.workspace = true
flowsdn-identity = { path = "../flowsdn-identity", version = "=0.14.0" }
[lints]
workspace = true
