[package]
name = "flowsdn-proxy"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
flowsdn-identity = { path = "../flowsdn-identity", version = "=0.14.0" }

[lints]
workspace = true
