[package]
name = "flowsdn-identity"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[features]
default = []
filter = ["dep:regex", "dep:serde_json", "dep:regex-syntax"]

[dependencies]
regex = { workspace = true, optional = true }
regex-syntax = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }

[lints]
workspace = true
