#!/usr/bin/env bash
# Write or check bpf-objects.lock, the committed pin of flowsdn's BPF datapath
# (spec 22 §3.8.4, ADR-0013 #245).
#
#   tools/bpf-objects-lock.sh write DIR   regenerate bpf-objects.lock from DIR
#   tools/bpf-objects-lock.sh check DIR   fail unless DIR and the embedded
#                                         objects match the committed lock
#
# DIR holds the objects tools/build-bpf.sh built from this commit. For each
# object the lock records `code-sha256`: the sha256 of the object with debug
# info, BTF and symbols stripped. cargo's metadata hash for path dependencies
# follows the checkout path and renames codegen units in the debug info, while
# the code, relocations, maps, .rodata.config and license are the same wherever
# the commit is built, so this is the hash a rebuild can reproduce. Objects the
# agent embeds also record `sha256`, the exact bytes in crates/flowsdn-agent/bpf,
# which the agent's unit tests check without a BPF toolchain.
set -euo pipefail
mode=${1:?usage: tools/bpf-objects-lock.sh write|check DIR}
dir=${2:?usage: tools/bpf-objects-lock.sh write|check DIR}
root=$(cd "$(dirname "$0")/.." && pwd)
tmp=${TMPDIR:-$root/tmp}
mkdir -p "$tmp"
lock="$root/bpf-objects.lock"

objects=(smoke local-delivery loader-features socket-context skb-ctx socket-lb)
embedded=(local-delivery socket-lb)

code_sha() {
    objcopy -I elf64-little --strip-all --remove-section=.BTF --remove-section=.BTF.ext \
        "$1" "$tmp/lock-code.o"
    sha256sum "$tmp/lock-code.o" | cut -d' ' -f1
}
is_embedded() {
    local e
    for e in "${embedded[@]}"; do [ "$e" = "$1" ] && return 0; done
    return 1
}

render() {
    local nightly linker o
    nightly=$(sed -n 's/^channel = "\(.*\)"$/\1/p' "$root/crates/flowsdn-bpf/rust-toolchain.toml")
    linker=$(sed -n 's/^ *version=\([0-9.]*\)$/\1/p' "$root/tools/build-bpf.sh")
    cat <<EOF
# bpf-objects.lock: the BPF datapath this commit builds (spec 22 §3.8.4, #245).
# Generated by tools/bpf-objects-lock.sh write from tools/build-bpf.sh output;
# test/build.sh checks it. Commit it with any change that alters an object.
# code-sha256: the object without debug info, BTF and symbols (path-independent).
# sha256: the exact bytes the agent embeds, for embedded objects.
toolchain = "$nightly"
bpf-linker = "$linker"
EOF
    for o in "${objects[@]}"; do
        [ -f "$dir/$o" ] || { echo "bpf-objects-lock: $dir/$o missing" >&2; exit 1; }
        printf '\n[[object]]\nname = "%s"\nvariant = "default"\nfeatures = []\n' "$o"
        printf 'code-sha256 = "%s"\n' "$(code_sha "$dir/$o")"
        if is_embedded "$o"; then
            printf 'embedded = "crates/flowsdn-agent/bpf/%s"\n' "$o"
            printf 'sha256 = "%s"\n' "$(sha256sum "$root/crates/flowsdn-agent/bpf/$o" | cut -d' ' -f1)"
        fi
    done
}

case "$mode" in
write)
    render >"$tmp/bpf-objects.lock.new"
    mv "$tmp/bpf-objects.lock.new" "$lock"
    echo "wrote $lock"
    ;;
check)
    render >"$tmp/bpf-objects.lock.built"
    status=0
    # An embedded copy whose code differs from this commit's build is stale.
    for o in "${embedded[@]}"; do
        if [ "$(code_sha "$root/crates/flowsdn-agent/bpf/$o")" != "$(code_sha "$dir/$o")" ]; then
            echo "bpf-objects-lock: crates/flowsdn-agent/bpf/$o is stale;" \
                "copy the $o tools/build-bpf.sh built and commit it" >&2
            status=1
        fi
    done
    if ! diff -u "$lock" "$tmp/bpf-objects.lock.built" >&2; then
        echo "bpf-objects-lock: the datapath changed; run tools/build-bpf.sh DIR &&" \
            "tools/bpf-objects-lock.sh write DIR and commit bpf-objects.lock" >&2
        status=1
    fi
    [ "$status" = 0 ] && echo "bpf-objects.lock matches this commit's objects"
    exit "$status"
    ;;
*)
    echo "usage: tools/bpf-objects-lock.sh write|check DIR" >&2
    exit 2
    ;;
esac
